######################## default configuration ####################
baseURL = "/"
title = "Mật Táo Đỏ Tâm An Bổ Máu"
# theme = "twenty-twenty-hugo"
languageName = "Vietnamese"
languageCode = "vi"
DefaultContentLanguage = "vi"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # disable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45


############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Trang chủ"
URL = "/"
weight = 1

[[menu.main]]
name = "Giới thiệu"
URL = "about/"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog/"
weight = 3

[[menu.main]]
name = "Liên hệ"
URL = "contact/"
weight = 4

# [[menu.main]]
# name = "Sample Page"
# URL = "sample-page/"
# weight = 5

# only desktop menu
[[menu.desktop]]
name = "Liên hệ"
URL = "contact/"
weight = 1


#################### default parameters ################################
[params]
# Meta data
description = "Mật Táo Đỏ Tâm An Bổ Máu 100% từ thiên nhiên"
author = "Mật Táo Đỏ Bổ Máu"

# favicon
[params.favicon]
favicon = "images/favicon.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# banner
[params.banner]
heading = "Mật Táo Đỏ Tâm An Bổ Máu 100% từ thiên nhiên"
image = "images/heading.png"

# blog
[params.blog]
heading = "4 chức năng chính của máu: Vận chuyển chất dinh dưỡng, dẫn truyền tín hiệu (báo đói, báo no, buồn ngủ, tới kỳ rụng dâu…), bảo vệ cơ thể trước các virus, vi khuẩn xâm nhập vào cơ thể, vận chuyển và đào thải rác thải qua gan và thận."

# call to action
[params.call_to_action]
enable = true
title = "Liên hệ với chúng tôi"
content = '<ul><li>Web: <a href="https://mattaodo.com/">mattaodo.com</a></li><li>Facebook <a href="https://facebook.com/mattaodo">facebook.com/mattaodo</a>.</li></ul><p>Bạn hãy điền nội dung tin nhắn vào form dưới đây và gửi cho chúng tôi. Chúng tôi sẽ trả lời bạn sau khi nhận được.</p>'
button_label = "Gửi đi"
button_url = "/"

# gallery
[params.gallery]
enable = true

[[params.gallery.gallery_item]]
image = "images/MTD_SP MOI_01.png"

[[params.gallery.gallery_item]]
image = "images/MTD_SP MOI_02.png"


# footer
[params.footer]
title = "Giới thiệu"
content = "Tổng hợp và chia sẻ các kiến thức liên quan về máu giúp bạn hiểu và sống khỏe hơn."
address = "123 Main Street <br> New York, NY 10001"
hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"
copyright = "Copyright @2018 by mattaodo.com"

############################# social site ########################
[params.social]
facebook = "https://facebook.com/mattaodo"
instagram = "https://www.instagram.com/mattaodobomau"
email = "kinhdoanh@tamannatural.vn"

